config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pets
  root to: "pets#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :species,:location, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:show, :update, :edit, :destroy]
  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])

  end

  def pet_params
    params.require(:pet).permit(:species, :location, :gender, :claimed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostKitty194</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col col-sm-8 col-sm-offset-2">
      <h3>Add A Pet</h3>
      <%= simple_form_for (@pet) do |f| %>
        <%= f.input :species, collection: ["dog", "cat", "rabbit"]%>
        <%= f.input :location %>
        <%= f.input :gender, collection: ["M", "F"], as: :radio_buttons%>
        <%= f.submit "Add a Pet" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render 'form' %>

app/views/pets/index.html.erb
<h1>Lost Pets</h1>
<div class="container">
  <div class="row">
    <% @pets.each do |pet|%>
      <div class="col col-xs-12 col-sm-4">
        <%= link_to pet.species, pet_path(pet) %>
        <p><%= pet.species %>,<%= pet.location %><%= pet.gender %></p>
      </div>
    <%end%>
  </div>
  <%= link_to "Add a Pet", new_pet_path, class: "btn btn-primary"  %>
</div>

app/views/pets/new.html.erb
<%= render 'form' %>

app/views/pets/show.html.erb
<p><%=@pet.species%>,<%= @pet.location %>,<%= @pet.gender %></p>
<%= link_to "delete", pet_path(@pet), method: :delete %>